"""Anthropic *contextual retrieval*: prepend a short, chunk-specific context (generated by
Claude on Bedrock) before embedding, so each chunk carries enough of its document to be
found. On by default; failures degrade gracefully to no-context (still embeddable)."""

from __future__ import annotations

from collections.abc import Callable

from moe.clients.bedrock import BedrockClient
from moe.models import Chunk, Document

_SYSTEM = (
    "You situate a text chunk within its source document to improve search retrieval. "
    "Reply with only the context — no preamble."
)


def _overview(doc: Document, max_chars: int = 1200) -> str:
    parts: list[str] = []
    if doc.title:
        parts.append(f"Title: {doc.title}")
    if doc.author:
        parts.append(f"Author: {doc.author}")
    body = " ".join(s.text for s in doc.sections)[:max_chars]
    parts.append(f"Overview: {body}")
    return "\n".join(parts)


def contextualize_chunks(
    doc: Document,
    chunks: list[Chunk],
    bedrock: BedrockClient,
    *,
    enabled: bool,
    progress: Callable[[int, int], None] | None = None,
) -> None:
    if not enabled:
        return
    overview = _overview(doc)
    for n, chunk in enumerate(chunks):
        heading = " › ".join(chunk.heading_path) if chunk.heading_path else "(top level)"
        prompt = (
            f"<document>\n{overview}\n</document>\n"
            f"<section>{heading}</section>\n"
            f"<chunk>\n{chunk.text}\n</chunk>\n\n"
            "Give a short 1-2 sentence context situating this chunk within the document, "
            "to improve retrieval of it. Answer only with the context."
        )
        try:
            chunk.context = bedrock.complete(prompt, system=_SYSTEM, max_tokens=120)
        except Exception:  # noqa: BLE001 — never let context-gen fail the ingest
            chunk.context = None
        if progress:
            progress(n + 1, len(chunks))
